language: ruby
cache: bundler
sudo: false
rvm: 2.7

install:
- gem update --system
- gem install bundler
- bundle install

script:
- bundle exec jekyll build

env:
  - JEKYLL_ENV=production

after_success:
- touch ./_site/.nojekyll

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
  github-token: $GITHUB_TOKEN
  local-dir: _site
  committer-from-gh: true
